services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: always
    env_file:
      - .env
    environment:
      - YC_TOKEN=${YANDEX_IAM_TOKEN}
      - YC_KEY_ID=${YANDEX_KEY_ID}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f bot.py || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
